# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  slack: circleci/slack@4.1
  heroku: circleci/heroku@1.2.6

jobs:
  build:
    docker:
      - image: cimg/node:14.17.0
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: yarn
      
      - run:
          name: "Build for production"
          command: yarn build

      - persist_to_workspace:
          root: .
          paths:
            - build
            - nginx.conf
            - default.conf.template
            - Dockerfile
            - Dockerfile
            - heroku.yml

  deploy:
    machine: true
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
      - heroku/install
      - attach_workspace:
          at: .
      - run:
          name: "Deploy"
          command: |
            heroku container:login
            heroku container:push web -a ${HEROKU_APP_NAME}
            heroku container:release web -a ${HEROKU_APP_NAME}

workflows:
  pipeline:
    jobs:
      - build:
          filters: &filters
            branches:
              only:
                - /^release\/[0-9]\.[0-9]\.[0-9]/
      - slack/on-hold:
          context: slack-secrets
          mentions: '<@U01A5Q0657U>, @rondinellimorais'
          filters: *filters
          requires:
            - build
      - wait-for-approval:
          type: approval
          filters: *filters
          requires:
            - build
            - slack/on-hold
      - deploy:
          context: slack-secrets
          filters: *filters
          requires:
            - wait-for-approval