# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  slack: circleci/slack@4.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Build"
          command: "echo Hello, World!"

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1

workflows:
  pipeline:
    jobs:
      - build:
          filters: &filters
            branches:
              only:
                - /^release\/[0-9]\.[0-9]\.[0-9]/
      - slack/on-hold:
          context: slack-secrets
          mentions: '<@U01A5Q0657U>, @rondinellimorais'
          filters: *filters
          requires:
            - build
      - wait-for-approval:
          type: approval
          filters:
            branches:
              only: /^release\/[0-9]\.[0-9]\.[0-9]/
          requires:
            - build
            - slack/on-hold
      - deploy:
          context: slack-secrets
          filters:
            branches:
              only: /^release\/[0-9]\.[0-9]\.[0-9]/
          requires:
            - wait-for-approval